---
- name: Configuring Glance Service on Controller Node!
  hosts: controller
  become: true
  ignore_errors: true
  vars_files:
    - vars/vars.yaml

  tasks:
    - name: Ensure glance database is present
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_unix_socket: "{{ mysql_socket }}"

    - name: Ensure glance DB user (localhost)
      mysql_user:
        name: "{{ db_user }}"
        update_password: always
        password: "{{ db_pass }}"
        host: "localhost"
        priv: "glance.*:ALL"
        state: present
        login_unix_socket: "{{ mysql_socket }}"

    - name: Ensure glance DB user (%)
      mysql_user:
        name: "{{ db_user }}"
        update_password: always
        password: "{{ db_pass }}"
        host: "%"
        priv: "glance.*:ALL"
        state: present
        login_unix_socket: "{{ mysql_socket }}"

    - name: Ensure glance is present
      apt:
        name:
          - "{{ glance_pkg }}"
        state: latest
        update_cache: yes

    - name: Updating the glance configuration file
      copy:
        src: "{{ glance_src }}"
        dest: "{{ glance_dest }}"

    - name: Ensure glance directory is present
      file:
        path: /root/glance
        state: directory

    - name: Ensure test iso file is present
      copy:
        src: "{{ img_src }}"
        dest: "{{ img_dest }}"
    
    - name: Ensure user.sh is present on /root/glance directory 
      copy:
        src: "{{ user_src }}"
        dest: "{{ user_dest }}"
        mode: '0755'

    - name: Ensure verify.sh is present on /root/glance directory 
      copy:
        src: "{{ verify_src }}"
        dest: "{{ verify_dest }}"
        mode: '0755'

    - name: Pupulating Image Service DB
      command: su -s /bin/sh -c "glance-manage db_sync" "{{ glance_user }}"
        
    - name: Ensure glance-api service is up and running
      service:
        name: glance-api
        state: restarted
        enabled: yes
