---
- name: Configuring administrative account by env variables on Controller Node!
  hosts: controller
  become: true
  ignore_errors: true
  vars:
    env_src: files/adminenv
    env_dest: /root/adminenv
  tasks:
    - name: Ensure env variables are present on root home directory
      copy:
        src: "{{ env_src }}"
        dest: "{{ env_dest }}"

    - name: =======NOTE==========
      debug:
        msg: "use source adminenv (filename) on root home directory of controller node to set env variables"
