---
- name: Configuring administrative account by env variables on Controller Node!
  hosts: controller
  become: true
  ignore_errors: true
  vars:
    env_src: files/adminenv
    env_dest: /root/adminenv
  tasks:
    - name: ensure env variables for admin is present
      copy:
        src: "{{ env_src }}"
        dest: "{{ env_dest }}"

    - name: Configuring env variables using script
      shell:
        cmd: source "{{ env_dest }}"
        executable: /bin/bash 
